/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test;

import java.awt.Color;
import java.awt.Dimension;
import static java.lang.Boolean.TRUE;
import static javafx.scene.paint.Color.color;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @author YOGA
 */
public class sw extends javax.swing.JFrame {

    /**
     * Creates new form sw
     */
    public sw() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new javax.swing.JPanel();
        iconmaxminclose = new javax.swing.JPanel();
        buttonclose = new javax.swing.JPanel();
        close = new javax.swing.JLabel();
        buttonmin = new javax.swing.JPanel();
        min = new javax.swing.JLabel();
        buttonmax = new javax.swing.JPanel();
        max = new javax.swing.JLabel();
        menu = new javax.swing.JPanel();
        menuIcon = new javax.swing.JPanel();
        list = new javax.swing.JPanel();
        hidemenu = new javax.swing.JPanel();
        hidemenubutton = new javax.swing.JLabel();
        setting = new javax.swing.JPanel();
        settingbutton = new javax.swing.JLabel();
        linehide = new javax.swing.JPanel();
        menuhide = new javax.swing.JPanel();
        dashboardview = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusTraversalPolicyProvider(true);
        setUndecorated(true);

        Header.setBackground(new java.awt.Color(29, 0, 125));
        Header.setPreferredSize(new java.awt.Dimension(800, 70));

        iconmaxminclose.setBackground(new java.awt.Color(29, 0, 125));
        iconmaxminclose.setPreferredSize(new java.awt.Dimension(150, 70));

        buttonclose.setBackground(new java.awt.Color(29, 0, 125));
        buttonclose.setPreferredSize(new java.awt.Dimension(50, 70));

        close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/iconfinder_cross-24_103181 (1).png"))); // NOI18N
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeMouseExited(evt);
            }
        });

        javax.swing.GroupLayout buttoncloseLayout = new javax.swing.GroupLayout(buttonclose);
        buttonclose.setLayout(buttoncloseLayout);
        buttoncloseLayout.setHorizontalGroup(
            buttoncloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttoncloseLayout.createSequentialGroup()
                .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        buttoncloseLayout.setVerticalGroup(
            buttoncloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttoncloseLayout.createSequentialGroup()
                .addComponent(close, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        buttonmin.setBackground(new java.awt.Color(29, 0, 125));
        buttonmin.setPreferredSize(new java.awt.Dimension(50, 70));

        min.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        min.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/iconfinder_minus-remove-delete-minimize_2931142.png"))); // NOI18N
        min.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minMouseExited(evt);
            }
        });

        javax.swing.GroupLayout buttonminLayout = new javax.swing.GroupLayout(buttonmin);
        buttonmin.setLayout(buttonminLayout);
        buttonminLayout.setHorizontalGroup(
            buttonminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(min, javax.swing.GroupLayout.PREFERRED_SIZE, 50, Short.MAX_VALUE)
        );
        buttonminLayout.setVerticalGroup(
            buttonminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(min, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
        );

        buttonmax.setBackground(new java.awt.Color(29, 0, 125));
        buttonmax.setPreferredSize(new java.awt.Dimension(50, 70));

        max.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        max.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/iconfinder_maximize-2_2561250.png"))); // NOI18N
        max.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                maxMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                maxMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                maxMouseExited(evt);
            }
        });

        javax.swing.GroupLayout buttonmaxLayout = new javax.swing.GroupLayout(buttonmax);
        buttonmax.setLayout(buttonmaxLayout);
        buttonmaxLayout.setHorizontalGroup(
            buttonmaxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(max, javax.swing.GroupLayout.PREFERRED_SIZE, 49, Short.MAX_VALUE)
        );
        buttonmaxLayout.setVerticalGroup(
            buttonmaxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonmaxLayout.createSequentialGroup()
                .addComponent(max, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout iconmaxmincloseLayout = new javax.swing.GroupLayout(iconmaxminclose);
        iconmaxminclose.setLayout(iconmaxmincloseLayout);
        iconmaxmincloseLayout.setHorizontalGroup(
            iconmaxmincloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, iconmaxmincloseLayout.createSequentialGroup()
                .addComponent(buttonmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(buttonclose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(iconmaxmincloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, iconmaxmincloseLayout.createSequentialGroup()
                    .addContainerGap(51, Short.MAX_VALUE)
                    .addComponent(buttonmax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(49, 49, 49)))
        );
        iconmaxmincloseLayout.setVerticalGroup(
            iconmaxmincloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonclose, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
            .addGroup(iconmaxmincloseLayout.createSequentialGroup()
                .addComponent(buttonmin, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(iconmaxmincloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(buttonmax, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addContainerGap(650, Short.MAX_VALUE)
                .addComponent(iconmaxminclose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addComponent(iconmaxminclose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(Header, java.awt.BorderLayout.PAGE_START);

        menu.setPreferredSize(new java.awt.Dimension(270, 450));
        menu.setLayout(new java.awt.BorderLayout());

        menuIcon.setBackground(new java.awt.Color(29, 0, 125));
        menuIcon.setPreferredSize(new java.awt.Dimension(100, 468));
        menuIcon.setVerifyInputWhenFocusTarget(false);
        menuIcon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        list.setBackground(new java.awt.Color(29, 0, 125));
        list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                listMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                listMouseExited(evt);
            }
        });

        javax.swing.GroupLayout listLayout = new javax.swing.GroupLayout(list);
        list.setLayout(listLayout);
        listLayout.setHorizontalGroup(
            listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        listLayout.setVerticalGroup(
            listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        menuIcon.add(list, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 5));

        hidemenu.setBackground(new java.awt.Color(29, 0, 125));
        hidemenu.setLayout(new java.awt.BorderLayout());

        hidemenubutton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hidemenubutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/iconfinder_back-alt_134226.png"))); // NOI18N
        hidemenubutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hidemenubuttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hidemenubuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hidemenubuttonMouseExited(evt);
            }
        });
        hidemenu.add(hidemenubutton, java.awt.BorderLayout.CENTER);

        menuIcon.add(hidemenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 100, 70));

        setting.setBackground(new java.awt.Color(29, 0, 125));
        setting.setLayout(new java.awt.BorderLayout());

        settingbutton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        settingbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/iconfinder_00-ELASTOFONT-STORE-READY_sliders_2738302.png"))); // NOI18N
        setting.add(settingbutton, java.awt.BorderLayout.CENTER);

        menuIcon.add(setting, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 100, 70));

        linehide.setBackground(new java.awt.Color(29, 0, 125));
        linehide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                linehideMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                linehideMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                linehideMouseExited(evt);
            }
        });

        javax.swing.GroupLayout linehideLayout = new javax.swing.GroupLayout(linehide);
        linehide.setLayout(linehideLayout);
        linehideLayout.setHorizontalGroup(
            linehideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        linehideLayout.setVerticalGroup(
            linehideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        menuIcon.add(linehide, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, -1, 10));

        menu.add(menuIcon, java.awt.BorderLayout.LINE_START);

        menuhide.setBackground(new java.awt.Color(19, 0, 83));

        javax.swing.GroupLayout menuhideLayout = new javax.swing.GroupLayout(menuhide);
        menuhide.setLayout(menuhideLayout);
        menuhideLayout.setHorizontalGroup(
            menuhideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );
        menuhideLayout.setVerticalGroup(
            menuhideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 468, Short.MAX_VALUE)
        );

        menu.add(menuhide, java.awt.BorderLayout.CENTER);

        getContentPane().add(menu, java.awt.BorderLayout.LINE_START);

        dashboardview.setBackground(new java.awt.Color(85, 115, 159));

        javax.swing.GroupLayout dashboardviewLayout = new javax.swing.GroupLayout(dashboardview);
        dashboardview.setLayout(dashboardviewLayout);
        dashboardviewLayout.setHorizontalGroup(
            dashboardviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );
        dashboardviewLayout.setVerticalGroup(
            dashboardviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 468, Short.MAX_VALUE)
        );

        getContentPane().add(dashboardview, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(800, 538));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    boolean a = true;
    
    public void changeColor(JPanel hover, Color rand){
        hover.setBackground(rand);
        
    }
    
    public void clickmenu(JPanel h1, JPanel h2, int numberbool){
        if(numberbool == 1){
            h1.setBackground(new Color(85, 119, 140));
            h2.setBackground(new Color(0, 52, 83));
        }
        else{
            h1.setBackground(new Color(0, 52, 83));
            h2.setBackground(new Color(85, 119, 140));
        }
    }
    
    public void hideshow(JPanel showhide, boolean dashboard, JLabel button){
        if(dashboard == true){
            showhide.setPreferredSize(new Dimension(50,showhide.getHeight()));
               changeImage(button,"/icon/menu.png");
        }
        else{
            showhide.setPreferredSize(new Dimension(270,showhide.getHeight()));
            changeImage(button,"/icon/iconfinder_back-alt_134226.png");
        }
    }
    
    public void changeImage(JLabel button, String reimg){
        ImageIcon aimg = new ImageIcon(getClass().getResource(reimg));
        button.setIcon(aimg);
    }
    
    private void closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseExited
        // TODO add your handling code here:
        changeColor(buttonclose, new Color(0, 52, 83));
    }//GEN-LAST:event_closeMouseExited

    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered
        // TODO add your handling code here:
        changeColor(buttonclose, new Color(85, 119, 140));
    }//GEN-LAST:event_closeMouseEntered

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closeMouseClicked

    private void maxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maxMouseClicked
        if(this.getExtendedState()!= sw.MAXIMIZED_BOTH){
            this.setExtendedState(sw.MAXIMIZED_BOTH);
        }
        else{
            this.setExtendedState(sw.NORMAL);
        }
        
    }//GEN-LAST:event_maxMouseClicked

    private void maxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maxMouseEntered
        // TODO add your handling code here:
        changeColor(buttonmax, new Color(85, 119, 140));
    }//GEN-LAST:event_maxMouseEntered

    private void maxMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maxMouseExited
        // TODO add your handling code here:
        changeColor(buttonmax, new Color(0, 52, 83));
    }//GEN-LAST:event_maxMouseExited

    private void hidemenubuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hidemenubuttonMouseEntered
        // TODO add your handling code here:
        changeColor(hidemenu, new Color(85, 119, 140));
    }//GEN-LAST:event_hidemenubuttonMouseEntered

    private void hidemenubuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hidemenubuttonMouseExited
        // TODO add your handling code here:
        changeColor(hidemenu, new Color(0, 52, 83));
    }//GEN-LAST:event_hidemenubuttonMouseExited

    private void hidemenubuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hidemenubuttonMouseClicked
        // TODO add your handling code here:
        clickmenu(hidemenu,setting,1);
        if(a==true){
            hideshow(menu,a,hidemenubutton);
            SwingUtilities.updateComponentTreeUI(this);
            a = false;
        }
        else{
            hideshow(menu,a, hidemenubutton);
            SwingUtilities.updateComponentTreeUI(this);
            a = true;
        }
        
    }//GEN-LAST:event_hidemenubuttonMouseClicked

    private void listMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listMouseEntered
        // TODO add your handling code here:
        changeColor(list, new Color(247, 78, 105));
    }//GEN-LAST:event_listMouseEntered

    private void listMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listMouseExited
        // TODO add your handling code here:
        changeColor(list, new Color(5, 10, 46));
    }//GEN-LAST:event_listMouseExited

    private void listMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listMouseClicked
        // TODO add your handling code here:
        clickmenu(setting,hidemenu,1);
    }//GEN-LAST:event_listMouseClicked

    private void linehideMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linehideMouseEntered
        // TODO add your handling code here:
        changeColor(linehide, new Color(8, 177, 150));
    }//GEN-LAST:event_linehideMouseEntered

    private void linehideMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linehideMouseExited
        // TODO add your handling code here:
        changeColor(linehide, new Color(5, 10, 46));
    }//GEN-LAST:event_linehideMouseExited

    private void linehideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linehideMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_linehideMouseClicked

    private void minMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minMouseEntered
        // TODO add your handling code here:
        changeColor(buttonmin, new Color(85, 119, 140));
    }//GEN-LAST:event_minMouseEntered

    private void minMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minMouseExited
        // TODO add your handling code here:
        changeColor(buttonmin, new Color(0, 52, 83));
    }//GEN-LAST:event_minMouseExited

    private void minMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minMouseClicked
        // TODO add your handling code here:
        if(this.getExtendedState()!= sw.HIDE_ON_CLOSE){
            this.setExtendedState(sw.HIDE_ON_CLOSE);
        }
        else{
            this.setExtendedState(sw.NORMAL);
        }
    }//GEN-LAST:event_minMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sw().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Header;
    private javax.swing.JPanel buttonclose;
    private javax.swing.JPanel buttonmax;
    private javax.swing.JPanel buttonmin;
    private javax.swing.JLabel close;
    private javax.swing.JPanel dashboardview;
    private javax.swing.JPanel hidemenu;
    private javax.swing.JLabel hidemenubutton;
    private javax.swing.JPanel iconmaxminclose;
    private javax.swing.JPanel linehide;
    private javax.swing.JPanel list;
    private javax.swing.JLabel max;
    private javax.swing.JPanel menu;
    private javax.swing.JPanel menuIcon;
    private javax.swing.JPanel menuhide;
    private javax.swing.JLabel min;
    private javax.swing.JPanel setting;
    private javax.swing.JLabel settingbutton;
    // End of variables declaration//GEN-END:variables
}
